from pygame import Vector2

FPS = 30

# screen
SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480
SCREEN_RES = (SCREEN_WIDTH, SCREEN_HEIGHT)

# bricks
BRICKS_PER_ROW = 10
BRICK_WIDTH = SCREEN_RES[0] / BRICKS_PER_ROW
LEFTMOST_BRICK_X = 0
RIGHTMOST_BRICK_X = SCREEN_WIDTH - BRICK_WIDTH
TOP_ROW_Y = SCREEN_HEIGHT * 0.15
BOTTOM_ROW_Y = SCREEN_HEIGHT * 0.45
NUMBER_OF_ROWS = 6
BRICK_HEIGHT = (BOTTOM_ROW_Y - TOP_ROW_Y) / NUMBER_OF_ROWS
BRICK_COLOR = (100, 100, 100)

# platform
PLATFORM_HEIGHT = BRICK_HEIGHT
PLATFORM_WIDTH = BRICK_WIDTH * 2
PLATFORM_Y = SCREEN_HEIGHT - PLATFORM_HEIGHT
PLATFORM_X = SCREEN_WIDTH/2 - 0.5*PLATFORM_WIDTH
PLATFORM_COLOR = (1.414213 * 100, 3.141562 * 10, 2.718281)
PLATFORM_POS = Vector2(PLATFORM_X, PLATFORM_Y)

# ball
BALL_RADIUS = 0.4 * PLATFORM_HEIGHT
BALL_X = PLATFORM_X + PLATFORM_WIDTH*0.5 - BALL_RADIUS * 0.5 
BALL_Y = PLATFORM_Y - BALL_RADIUS
BALL_POS = Vector2(BALL_X, BALL_Y)
BALL_COLOR = (1.12*100, 3.58*10, 1.32)
BALL_START_VELOCITY = Vector2(0, -12)